
services:
  db01:
   build:
      context: ./Docker-files/db
   image: yaminiobinendi/vprodb
   container_name: db01
   ports:
      - "3306:3306"
   volumes: 
      - vprodbdata:/var/lib/mysql
   environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE =accounts
    
  mc01:
   image: memcached
   ports:
      - "11211:11211"
    
  rmq01:
   image: rabbitmq
   ports:
      - "5672:5672"
   environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test

  app01:
   build:
      context: ./Docker-files/app
   image: yaminiobinendi/vproapp
   container_name: app01
   ports:
      - "8080:8080"
   volumes: 
      - vproappdata:/usr/local/tomcat/webapps

  web01:
   build:
      context: ./Docker-files/web
   image: yaminiobinendi/vproweb
   container_name: web01
   ports:
      - "80:80" 


volumes:
  vprodbdata: {}
  vproappdata: {}

